music-tracker:
   target: dev
   outputs:
     dev:
       type: duckdb
       path: "{{ env_var('DUCKDB_PATH', '../data/music_tracker.duckdb') }}"
       threads: 1
       settings:
         memory_limit: 800MB
         threads: 1
         max_memory: 800MB

     local:
       type: duckdb
       path: "../data/music_tracker.duckdb"
       threads: 4
       extensions:
         - httpfs
         - parquet
       settings:
         memory_limit: 4GB
         threads: 4
