version: 2

sources:
  - name: lh
    meta:
      external_location: "../data/src/{name}/*.parquet"
    tables:
      - name: tracks_played
      - name: spotify_artists
      - name: spotify_artist_genre
      - name: mbz_artist_info
      - name: spotify_albums
      - name: mbz_area_hierarchy
      - name: cities_with_lat_long

  - name: rt
    meta:
      external_location: "{% if target.name == 'dev' %}/app/data{% else %}../data{% endif %}/{name}.csv"
    tables:
      - name: recently_played
