version: 2

sources:
  - name: lh
    meta:
      external_location: "data/src/{name}/*.snappy.parquet"
    tables:
      - name: tracks_played
      - name: spotify_artists
      - name: spotify_artist_genre
      - name: mbz_artist_info
      - name: spotify_albums
      - name: mbz_area_hierarchy
      - name: cities_with_lat_long