version: 2

sources:
  - name: raw
    schema: main

    quoting:
      database: false
      schema: false
      identifier: false
      
    tables:
      - name: tracks_played
      - name: spotify_artists
      - name: spotify_artist_genre
      - name: mbz_artist_info
      - name: spotify_albums
      - name: mbz_area_hierarchy
      - name: cities_with_lat_long